-- 코드를 작성해주세요
SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.LENGTH IN (SELECT MAX(FI2.LENGTH)
                    FROM FISH_INFO FI2
                    WHERE FI.FISH_TYPE = FI2.FISH_TYPE )
ORDER BY FI.ID